### ISSUE TITLE
fails to init (missing module livereload)

### ISSUE THREAD

**Issue by jtmoon79** [icyphox/vite#1]
Using Debian 9

```
$ docker run -ti --rm python:3.7 bash --login
# within docker instance
$ pip install vite
$ vite init /tmp/project1
Traceback (most recent call last):
  File "/usr/local/bin/vite", line 6, in <module>
    from vite.cli import main
  File "/usr/local/lib/python3.7/site-packages/vite/cli.py", line 3, in <module>
    from vite import vite
  File "/usr/local/lib/python3.7/site-packages/vite/vite.py", line 19, in <module>
    from livereload import Server
ModuleNotFoundError: No module named 'livereload'
```

**Comment by icyphox** [comment]
Oh okay, I’ll have to update the `requirements.txt` file with that dependency. Must’ve missed it. 

For now just `pip3 install livereload --user` and you should be good.
